services:
  - type: web
    name: authentick-backend
    runtime: docker
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: authentick-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: authentick-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: authentick-db
          property: databaseName
      - key: DATABASE_USER
        fromDatabase:
          name: authentick-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: authentick-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false # Set this to your Vercel URL later

databases:
  - name: authentick-db
    plan: free
    databaseName: authentick
    user: authentick_user
